version: "3.8"

services:
  lapoker-api:
    build: .
    container_name: lapoker-api
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lapoker-api.rule=Host(`api.lapoker.com.br`)"
      - "traefik.http.routers.lapoker-api.entrypoints=websecure"
      - "traefik.http.routers.lapoker-api.tls.certresolver=mytlschallenge"
      - "traefik.http.services.lapoker-api.loadbalancer.server.port=8000"
    networks:
      - n8n_default

networks:
  n8n_default:
    external: true